server:
  port: 18085
spring:
  application:
    name: sentinel-spring-cloud-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      # Add your routes here.
      - id: aliyun_route
        uri: https://www.aliyun.com/
        predicates:
        - Path=/product/**
      - id: httpbin_route
        uri: https://httpbin.org
        predicates:
        - Path=/httpbin/**
        filters:
        - RewritePath=/httpbin/(?<segment>.*), /$\{segment}

    sentinel:
#      datasource.ds.nacos:
#            dataId: ${spring.application.name}-sentinel
#            groupId: DEFAULT_GROUP
#            rule-type: flow
#            server-addr: localhost:8848
#            namespace: 4bed6aa1-4cff-4244-9a5c-ef8add9cbb05
      transport:
        dashboard: localhost:8899
      filter:
        enabled: true
#      scg.fallback:
#          mode: response
#          response-status: 444
#          response-body: 1234
      scg:
        order: -100


management.endpoints.web.exposure.include: "*"