#spring:
#  data:
#    master:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
#    slave:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://rm-bp10dof7uwl5dq45yzo.mysql.rds.aliyuncs.com:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
#      username: guoly
#      password: 131719Wxz

spring:
  datasource:
    master:
      pool-name: master
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      maximum-pool-size: 10
      minimum-idle: 5
    slave:
      - pool-name: slave1
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-bp10dof7uwl5dq45yzo.mysql.rds.aliyuncs.com:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
        username: guoly
        password: 131719Wxz
        maximum-pool-size: 10
        minimum-idle: 5
#      - pool-name: slave2
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/payment
#        username: user_R
#        password: 123456
#        maximum-pool-size: 10
#        minimum-idle: 5


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.msdb.db.entity


server:
  port: 7878

#spring:
#  datasource:
#    connection-init-sqls: set names utf8mb4
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/im-block?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root

