spring:
  data:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-bp10dof7uwl5dq45yzo.mysql.rds.aliyuncs.com:3306/im-block?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
      username: guoly
      password: 131719Wxz