package com.example.msdb.db.dao;

import com.example.msdb.db.entity.GatewayRoutes;
import com.example.msdb.db.entity.GatewayRoutesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatewayRoutesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    long countByExample(GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int deleteByExample(GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int insert(GatewayRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int insertSelective(GatewayRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    List<GatewayRoutes> selectByExampleWithBLOBs(GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    List<GatewayRoutes> selectByExample(GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    GatewayRoutes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") GatewayRoutes record, @Param("example") GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") GatewayRoutes record, @Param("example") GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    int updateByExample(@Param("record") GatewayRoutes record, @Param("example") GatewayRoutesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:31 CST 2021
     */
    int updateByPrimaryKeySelective(GatewayRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:31 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(GatewayRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:31 CST 2021
     */
    int updateByPrimaryKey(GatewayRoutes record);
}