package com.example.msdb.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GatewayRoutesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public GatewayRoutesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(String value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(String value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(String value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(String value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(String value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(String value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLike(String value) {
            addCriterion("route_id like", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotLike(String value) {
            addCriterion("route_id not like", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<String> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<String> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(String value1, String value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(String value1, String value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteUriIsNull() {
            addCriterion("route_uri is null");
            return (Criteria) this;
        }

        public Criteria andRouteUriIsNotNull() {
            addCriterion("route_uri is not null");
            return (Criteria) this;
        }

        public Criteria andRouteUriEqualTo(String value) {
            addCriterion("route_uri =", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriNotEqualTo(String value) {
            addCriterion("route_uri <>", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriGreaterThan(String value) {
            addCriterion("route_uri >", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriGreaterThanOrEqualTo(String value) {
            addCriterion("route_uri >=", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriLessThan(String value) {
            addCriterion("route_uri <", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriLessThanOrEqualTo(String value) {
            addCriterion("route_uri <=", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriLike(String value) {
            addCriterion("route_uri like", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriNotLike(String value) {
            addCriterion("route_uri not like", value, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriIn(List<String> values) {
            addCriterion("route_uri in", values, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriNotIn(List<String> values) {
            addCriterion("route_uri not in", values, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriBetween(String value1, String value2) {
            addCriterion("route_uri between", value1, value2, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteUriNotBetween(String value1, String value2) {
            addCriterion("route_uri not between", value1, value2, "routeUri");
            return (Criteria) this;
        }

        public Criteria andRouteOrderIsNull() {
            addCriterion("route_order is null");
            return (Criteria) this;
        }

        public Criteria andRouteOrderIsNotNull() {
            addCriterion("route_order is not null");
            return (Criteria) this;
        }

        public Criteria andRouteOrderEqualTo(Integer value) {
            addCriterion("route_order =", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderNotEqualTo(Integer value) {
            addCriterion("route_order <>", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderGreaterThan(Integer value) {
            addCriterion("route_order >", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_order >=", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderLessThan(Integer value) {
            addCriterion("route_order <", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderLessThanOrEqualTo(Integer value) {
            addCriterion("route_order <=", value, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderIn(List<Integer> values) {
            addCriterion("route_order in", values, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderNotIn(List<Integer> values) {
            addCriterion("route_order not in", values, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderBetween(Integer value1, Integer value2) {
            addCriterion("route_order between", value1, value2, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andRouteOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("route_order not between", value1, value2, "routeOrder");
            return (Criteria) this;
        }

        public Criteria andAutoRouteIsNull() {
            addCriterion("auto_route is null");
            return (Criteria) this;
        }

        public Criteria andAutoRouteIsNotNull() {
            addCriterion("auto_route is not null");
            return (Criteria) this;
        }

        public Criteria andAutoRouteEqualTo(String value) {
            addCriterion("auto_route =", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteNotEqualTo(String value) {
            addCriterion("auto_route <>", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteGreaterThan(String value) {
            addCriterion("auto_route >", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteGreaterThanOrEqualTo(String value) {
            addCriterion("auto_route >=", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteLessThan(String value) {
            addCriterion("auto_route <", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteLessThanOrEqualTo(String value) {
            addCriterion("auto_route <=", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteLike(String value) {
            addCriterion("auto_route like", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteNotLike(String value) {
            addCriterion("auto_route not like", value, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteIn(List<String> values) {
            addCriterion("auto_route in", values, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteNotIn(List<String> values) {
            addCriterion("auto_route not in", values, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteBetween(String value1, String value2) {
            addCriterion("auto_route between", value1, value2, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andAutoRouteNotBetween(String value1, String value2) {
            addCriterion("auto_route not between", value1, value2, "autoRoute");
            return (Criteria) this;
        }

        public Criteria andHealthPathIsNull() {
            addCriterion("health_path is null");
            return (Criteria) this;
        }

        public Criteria andHealthPathIsNotNull() {
            addCriterion("health_path is not null");
            return (Criteria) this;
        }

        public Criteria andHealthPathEqualTo(String value) {
            addCriterion("health_path =", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathNotEqualTo(String value) {
            addCriterion("health_path <>", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathGreaterThan(String value) {
            addCriterion("health_path >", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathGreaterThanOrEqualTo(String value) {
            addCriterion("health_path >=", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathLessThan(String value) {
            addCriterion("health_path <", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathLessThanOrEqualTo(String value) {
            addCriterion("health_path <=", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathLike(String value) {
            addCriterion("health_path like", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathNotLike(String value) {
            addCriterion("health_path not like", value, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathIn(List<String> values) {
            addCriterion("health_path in", values, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathNotIn(List<String> values) {
            addCriterion("health_path not in", values, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathBetween(String value1, String value2) {
            addCriterion("health_path between", value1, value2, "healthPath");
            return (Criteria) this;
        }

        public Criteria andHealthPathNotBetween(String value1, String value2) {
            addCriterion("health_path not between", value1, value2, "healthPath");
            return (Criteria) this;
        }

        public Criteria andIsEblIsNull() {
            addCriterion("is_ebl is null");
            return (Criteria) this;
        }

        public Criteria andIsEblIsNotNull() {
            addCriterion("is_ebl is not null");
            return (Criteria) this;
        }

        public Criteria andIsEblEqualTo(Boolean value) {
            addCriterion("is_ebl =", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblNotEqualTo(Boolean value) {
            addCriterion("is_ebl <>", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblGreaterThan(Boolean value) {
            addCriterion("is_ebl >", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_ebl >=", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblLessThan(Boolean value) {
            addCriterion("is_ebl <", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblLessThanOrEqualTo(Boolean value) {
            addCriterion("is_ebl <=", value, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblIn(List<Boolean> values) {
            addCriterion("is_ebl in", values, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblNotIn(List<Boolean> values) {
            addCriterion("is_ebl not in", values, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ebl between", value1, value2, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsEblNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ebl not between", value1, value2, "isEbl");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gateway_routes
     *
     * @mbg.generated do_not_delete_during_merge Thu May 20 17:18:30 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gateway_routes
     *
     * @mbg.generated Thu May 20 17:18:30 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}